site_name: Lernez Ido!
theme:
  name: material

  custom_dir: overrides

  palette: 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: deep purple
      accent: deep purple

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: deep purple
      accent: deep purple

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Home: https://lernez.github.io

extra:
  social:
    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/r/Ido
      name: r/Ido subreddit
    - icon: fontawesome/brands/github
      link: https://github.com/lernez/lernez.github.io
      name: This site's source code

copyright: The source code of this website and the content therein are subject to the <a href="https://www.gnu.org/licenses/agpl-3.0.html">AGPLv3 licence</a>.

repo_url: https://github.com/lernez/lernez.github.io
repo_name: lernez/lernez.github.io
edit_uri: edit/main/docs/

markdown_extensions:
  - abbr # use abbreviations, like hovertext
  - admonition # note boxes
  - attr_list # add html and css attributes to most stuff
  - def_list # definitions like MediaWiki
  - footnotes # footnotes
  - md_in_html # allow use of markdown in html
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - tables # must
  - pymdownx.caret # insert, superscript
  - pymdownx.mark # highlighting
  - pymdownx.tilde # delete, subscript
  - pymdownx.details # collapsable note boxes for admonition
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true